### ISSUE TITLE
I got some error

### ISSUE THREAD

**Issue by H-Haynes** [fetlife/vscode-vue-languageservice#1]
when I use `tsc` compile my project, some error has been throw:

```javascript

/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:12
            const matchs = nodeText.matchAll(reg);
                                    ^
TypeError: nodeText.matchAll is not a function
    at visChild (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:12:37)
    at visChild (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:25:17)
    at visChild (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:25:17)
    at visChild (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:25:17)
    at visChild (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:25:17)
    at parse (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:6:5)
    at ReactiveEffect.textDocuments [as fn] (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/use/useSfcStyles.js:31:58)
    at ReactiveEffect.run (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
    at ComputedRefImpl.get value [as value] (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1075:39)
    at ReactiveEffect.cssModuleClasses [as fn] (/home/gitlab-runner/builds/Z_Raszwk/0/gitlab/root/vite-vue/node_modules/vscode-vue-languageservice/out/use/useSfcTemplateScript.js:15:78)

```

**Comment by woden0415** [comment]
I got this problem
